module.exports = {
  "cities" : [
    "San Francisco CA",
    "Bay Area CA",
    "San Diego CA",
    "Los Angeles CA",
    "Portlang OR",
    "Seattle WA",
    "Denver CO",
    "Boulder CO",
    "Boston MA",
    "Atlanta GA",
    "Washington DC",
    "Chicago IL",
    "Detroit MI",
    "Raleigh NC",
    "Charlotte NC",
    "New York City NY",
    "Austin TX",
    "Dallas TX",
    "Houston TX",
  ],

  "states" : [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
  ],

  "countries" : ['USA']
}
